In [1]:
import pandas as pd

df = pd.read_csv('data.csv')

new_df = df.dropna()

print(new_df.to_string())

     Name  Age        City  Score
0     Ali   22      Lahore     85
1    Sara   24     Karachi     92
2   Ahmed   21   Islamabad     78
3  Ayesha   23      Lahore     88
4   Hamza   25  Faisalabad     74
5  Zainab   22      Multan     95

In [2]:
import pandas as pd

df = pd.read_csv('data.csv')

df.dropna(inplace = True)

print(df.to_string())

     Name  Age        City  Score
0     Ali   22      Lahore     85
1    Sara   24     Karachi     92
2   Ahmed   21   Islamabad     78
3  Ayesha   23      Lahore     88
4   Hamza   25  Faisalabad     74
5  Zainab   22      Multan     95

In [3]:
import pandas as pd

df = pd.read_csv('data.csv')

df.fillna(130, inplace = True)

     Name  Age        City  Score
0     Ali   22      Lahore     85
1    Sara   24     Karachi     92
2   Ahmed   21   Islamabad     78
3  Ayesha   23      Lahore     88
4   Hamza   25  Faisalabad     74
5  Zainab   22      Multan     95

In [9]:
import pandas as pd

df = pd.read_csv('data.csv')

df.fillna({"Score": 130}, inplace=True)

     Name  Age        City  Score
0     Ali   22      Lahore     85
1    Sara   24     Karachi     92
2   Ahmed   21   Islamabad     78
3  Ayesha   23      Lahore     88
4   Hamza   25  Faisalabad     74
5  Zainab   22      Multan     95

In [10]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Score"].mean()

df.fillna({"Score": x}, inplace=True)

     Name  Age        City  Score
0     Ali   22      Lahore     85
1    Sara   24     Karachi     92
2   Ahmed   21   Islamabad     78
3  Ayesha   23      Lahore     88
4   Hamza   25  Faisalabad     74
5  Zainab   22      Multan     95

In [13]:
print("Mean:", x)

df.fillna({"Score": x}, inplace=True)

print(df)

Mean: 85.33333333333333
     Name  Age        City  Score
0     Ali   22      Lahore     85
1    Sara   24     Karachi     92
2   Ahmed   21   Islamabad     78
3  Ayesha   23      Lahore     88
4   Hamza   25  Faisalabad     74
5  Zainab   22      Multan     95

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Score"].median()
print("Mediun:", x)

df.fillna({"Score": x}, inplace=True)

print(df)